### ISSUE TITLE
Width of prompt matching width of terminal bug

### ISSUE THREAD

**Issue by ashort96** [iDestyKK/CN_Experience#3]
There is an issue where the if the widths of the prompt matches the width of the terminal, the prompt continuously moves up deleting all content beforehand. This issue can be fixed by removing (or commenting out):

```
TRAPALARM() {
    zle reset-prompt
}
```

on lines 308-310 in configs/zsh/.zsh.prompt

Because of this, though, the time is not reflected accurately in the prompt since it no longer updates.

**Comment by iDestyKK** [comment]
Unfortunately `TRAPALARM` is required for the realtime clock to operate. zsh itself actually has a memory leak that causes it to use more memory every time the clock updates as well. Unfortunately, it has to refresh the entire prompt. Since it has to go up 1 line every time it refreshes, that's probably what's causing the prompt to go up per refresh when the bar is exactly the length of the terminal.

I'm tempted to consider doing path compression (e.g. `~/files/important_project/foo/bar` -> `~/ ... /bar` or vim-style `~/f/i/f/bar`). It seems like a popular option that other zsh themes are doing. It'll also prevent the bar from stretching out too much due to large paths.
